DROP DATABASE IF EXISTS ;

CREATE DATABASE Art;
USE Art;

CREATE TABLE Users(
    ID VARCHAR(100) NOT NULL,
    PW VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
    FLAG INT DEFAULT 0,
    AUTHKEY VARCHAR(100),
    ADDR VARCHAR(50) NOT NULL,
    PHONE VARCHAR(50) NOT NULL,
    ART INT DEFAULT 0 --아티스트인지의 여부
);

CREATE TABLE Goodies(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GNAME VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(5000) NOT NULL,
    TA INT NOT NULL, --목표금액
    CA INt DEFAULT 0, --현재금액
    GCATEGORIZE VARCHAR(50) NOT NULL, --굿즈의 종류
    SCATEGORIZE VARCHAR(50) NOT NULL, --공연의 종류
    USER VARCHAR(100),
    VIEWS INT DEFAULT 0, --조회수
    show INT NOT NULL
);

CREATE TABLE Show{
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORIZE VARCHAR(50),
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(5000) NOT NULL,
    VIEWS INT DEFAULT 0
}

--유저의 펀딩여부 확인용 테이블
CREATE TABLE Fund(
    ID INT, --굿즈의 아이디 
    USER VARCHAR(100)
);

--유저의 취향확인용 테이블
CREATE TABLE Recommend(
    USER VARCHAR(100) NOT NULL PRIMARY KEY,
    Concert INT DEFAULT 0,
    Drama INT DEFAULT 0,
    Opera INT DEFAULT 0,
    Dance INT DEFAULT 0,
    Musical INT DEFAULT 0,
    PhotoCard INT DEFAULT 0,
    KeyRing INT DEFAULT 0,
    PhoneCase INT DEFAULT 0,
    Charact INT DEFAULT 0,
    Gother INT DEFAULT 0,
    Sother INT DEFAULT 0
);
